---
layout: cv
title: Ash Uchida's Resume
---
Aspiring Software Engineer and Data Analyst

<div id="webaddress">
<a href="https://ash-uchida.github.io/wdd131/Portfolio/">My other portfolio</a>
| <a href="https://www.linkedin.com/in/ash-uchida/">My Linkden</a>
</div>


## Currently

I'm a student at Brigham Young University - Idaho 


#### Specializing in 

Bachelor of Computer Science
Minor of Data Science
Certificate in Cyber Security



#### Research interests

Ham radio, Cloud Computing, Databases



## Education

Brigham Young University - Idaho 
`September 2024 - now`



## Awards

`2026`
2nd Place Hackathon Winner

`2024 – 2026`
BYU-Idaho Academic Scholarship

`2020 – 2024`
Huron Heights Secondary School Honor Roll



## Projects

#### HackUSU 
`Feb 27-28 2026`
Built a governed analytics platform (“Sales Dashboard Factory
”) in a 17-hour hackathon sprint, earning 2nd place in the
Data App Factory challenge.
Developed a Streamlit-based application with conversational AI that converts natural language into secure, validated SQL
queries using Databricks and Unity Catalog.
Collaborated in a fast-paced team environment to design role-based data access, implement SQL guardrails, and deploy a
scalable, secure data solution.

#### Zoom Zone - Personal Project
`Dec 2025 – Jan 2026`
Developed a full stack scheduling platform that automated 100% of meeting creation by integrating Google Calendar and
Zoom APIs to eliminate double booking.
Engineered a serverless backend on Vercel using Supabase and secure OAuth token handling, maintaining data
persistence for all user bookings.
Implemented a Calendly-style booking interface that displays real-time availability and allows users to schedule meetings
through a guided flow.

#### Secretary of the Hackathon Society 
`Feb 2025 – Nov 2025`
Facilitated team alignment by documenting committee discussions and distributing action items to ensure all project goals
were met.
Coordinated logistics for 35+ teams and 150+ attendees, overseeing the seamless distribution of information and food
throughout the 24 hour event.
Evaluated participant projects as a judge and managed the creation and presentation of official awards for the closing
ceremony.

## Experience

`Jul 2025 – Sept 2025`
__Team Member at Target__, Queen Creek, Arizona

- Consistently reported at 4 AM to unload delivery trucks.
- Collaborated with a team to unload and organize high volume shipments within tight 2 hour windows.
- Processed and distributed 500+ items of merchandise daily with high accuracy

`Aug 2023 – Aug 2024`
__Team Member at Tim Hortons__, Keswick, Ontario, Canada

- Collaborated with a team of 10+ to maintain 30 second service speeds in a high volume environment.
- erved 200+ customers daily with a 98% order accuracy rate through clear, efficient communication.
- Resolved 100% of customer issues on-site using professional conflict resolution to ensure guest satisfaction.



<!-- ### Footer

Last updated: March 30 -->