---
title: "Client Report -How good is it, really?"
subtitle: "Course DS 250"
author: "Ash Uchida"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *
from sklearn.model_selection import train_test_split
from sklearn import metrics
import requests
import io
import polars.selectors as cs
# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# import your data here using polars and the URL
url = "https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv"

response = requests.get(url)

df = pl.read_csv(io.BytesIO(response.content))
df
```

## QUESTION 1

1. __Describe the quality of your classification model using 2-3 different evaluation metrics.__ You also need to explain how to define/interpret each of the evaluation metrics you use.  

_The different evaluation metrics that I used were classification report and confusion matrix. USing these we can then see the percentage of how acurate our predictions were. from what we did we got high 80's when it came to our predictions which is a good percentage for our predictions_

```{python}
x = df.select((cs.numeric()).exclude(["before1980","yrbuilt"]))
y = df.select('before1980')

```

```{python}
# Include and execute your code here
# Don't forget, you need another import statement to import the desired ML model from sklearn
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=12394, train_size=.8)

```

```{python}
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Use .to_series() to flatten the target column without manual numpy calls
y_train_series = y_train.to_series()

tree_classifier = DecisionTreeClassifier()
tree_classifier.fit(x_train, y_train_series)

forest_classifier = RandomForestClassifier()
forest_classifier.fit(x_train, y_train_series)

knee_classifier = KNeighborsClassifier()
knee_classifier.fit(x_train, y_train_series)
```

```{python}
from sklearn.metrics import classification_report, confusion_matrix

y_pred = tree_classifier.predict(x_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))
```

## QUESTION 2

1. __Justify your classification model by discussing the most important features selected by your model.__ This discussion should include a plot of permutation importance values for the most important features. Were there any features you thought would be importance but weren't?

_we can use the permutation importance function to go through our data and sort what their imporacnce is in descding order to see the top 10 most important piece of data. As seen we printed out a table with the top 10 results_

```{python}
# Include and execute your code here
from sklearn.inspection import permutation_importance

# Calculate importance (keep these as separate variables!)
result = permutation_importance(forest_classifier, x_test, y_test, n_repeats=5, random_state=4552)

feature_names = x.columns

#  Create the Polars DataFrame for plotting
importance_df = pl.DataFrame({
    'vars': feature_names,
    'importance': result.importances_mean
}).sort('importance', descending=True)

importance_df.head(10) # Show top 10

```


## QUESTION 3

1. __For the 3 most important features, explain their relationship to the target variable. Use a plot to illustrate the relationship.__ (3 plots minimum)

_The three most important features are: gartype_Att, numbaths, stories. So we just need to graph these out compared to the original before1980 to see the trend_

```{python}
# Include and execute your code here
(
  ggplot(df, aes(x="gartype_Att", y="before1980"))
  +geom_bar(stat='summary')
  + labs(title="Attached Garage", y="Rate", x="Has Attached Garage")
)

```
```{python}
(
  ggplot(df,aes(x="numbaths",y="before1980"))
  +geom_line(stat="summary")
  +labs(title="Number of Baths", x="Baths")
)
```

```{python}
(
  ggplot(df,aes(x="stories", y="before1980"))
  +geom_bar(stat="summary")
  +labs(title="Number of stories", x="Stories")
)
```