---
title: "Client Report - Show me!"
subtitle: "Course DS 250"
author: "Ash Uchida"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *
from sklearn.model_selection import train_test_split
from sklearn import metrics
import requests
import io
import polars.selectors as cs
# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# import your data here using polars and the URL
url = "https://raw.githubusercontent.com/byuidatascience/data4dwellings/master/data-raw/dwellings_ml/dwellings_ml.csv"

response = requests.get(url)

df = pl.read_csv(io.BytesIO(response.content))
df
```

## QUESTION 1

1. __Repeat the classification exercise using 2 different algorithms/models. Explain the differences between the 3 models__ (your original one, and the 2 new ones for this task).

_we just need to repeat the proceess for the 3 different classifiers_
```{python}
x = df.select((cs.numeric()).exclude(["before1980","yrbuilt"]))
y = df.select('before1980')

```

```{python}
# Include and execute your code here
# Don't forget, you need another import statement to import the desired ML model from sklearn
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=12394, train_size=.8)

```

```{python}
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Use .to_series() to flatten the target column without manual numpy calls
y_train_series = y_train.to_series()

tree_classifier = DecisionTreeClassifier()
tree_classifier.fit(x_train, y_train_series)

forest_classifier = RandomForestClassifier()
forest_classifier.fit(x_train, y_train_series)

knee_classifier = KNeighborsClassifier()
knee_classifier.fit(x_train, y_train_series)
```

```{python}
from sklearn.metrics import classification_report

y_pred = tree_classifier.predict(x_test)
y_pred2 = forest_classifier.predict(x_test)
y_pred3 = knee_classifier.predict(x_test)

print(classification_report(y_test, y_pred))
print(classification_report(y_test, y_pred2))
print(classification_report(y_test, y_pred3))

```


## QUESTION 2

1. For each model (your original one, and the 2 new ones for this task), display the classification report and the permutation importances for the most important features.  Discuss which model you would recommend to the Client and why.

_To do this I created 3 tables for the 3 different model used: desicon tree, random forest and kneigbors. After looking and comparing them the most important feautures our clients should focus on are: num_baths, gartype_att, stories, arcstyle_ONE-STORY, livearea, netprice_

```{python}
# Include and execute your code here
from sklearn.inspection import permutation_importance

tree_importance = permutation_importance(tree_classifier, x_test, y_test, n_repeats=2, random_state=107)
forest_importance = permutation_importance(forest_classifier, x_test, y_test, n_repeats=2, random_state=103)
knee_importance = permutation_importance(knee_classifier, x_test, y_test, n_repeats=1, random_state=123)

```

```{python}
feature_names = x.columns

#  Create the Polars DataFrame for plotting
importance_tree = pl.DataFrame({
    'vars': feature_names,
    'importance': tree_importance.importances_mean,
    'model': 'Decision Tree'
}).sort('importance', descending=True)


importance_tree.head(10)

```

```{python}
importance_forest = pl.DataFrame({
    'vars': feature_names,
    'importance': forest_importance.importances_mean,
    'model': 'Random Forest'
}).sort('importance', descending=True)

importance_forest.head(10)
```

```{python}
importance_knee = pl.DataFrame({
    'vars': feature_names,
    'importance': knee_importance.importances_mean,
    'model': 'K-Nearest Neighbors'
}).sort('importance', descending=True)

importance_knee.head(10)
```