---
title: "Client Report - Flights: Column Aggregation"
subtitle: "Course DS 250"
author: "Ash Uchida"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
df
```

## QUESTION 1

1. __Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the 
total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

_By using the group by for the airport name we can then do the calculations for all 4 columns givin in the question._

```{python}
# Include and execute your code here
delays = (
  df.group_by('airport_name')
  .agg(
    pl.col('num_of_flights_total').sum().alias('Total_flights'),  #total number of flights
    pl.col('num_of_delays_total').sum().alias('Total_delays'),   #total number of delayed flights
    (pl.col('num_of_delays_total').sum() / pl.col('num_of_flights_total').sum()).alias('proportion_delayed'),    #proportion of delayed flights
    ((pl.col('minutes_delayed_total').sum() / pl.col('num_of_flights_total').sum()) / 60).alias('avg_delay_hours'),   #average delay time in hours.
  )
)
delays
```

## QUESTION 2

__Create a barplot showing the proportion of all flights that are delayed at each airport. Describe what you learn from this graph.__  

_As for this bar chart one can see that there are noticable differences when it come to delays. The airports that has the most delays are Atlanta and Chicago. Whereas, San Fransico and Denver seem to hold the middle ground, and the rest are relativly low. One would have to guess that the airport with less delays are significantly smaller than those with more delays._

```{python}
# Include and execute your code here
(
  ggplot(delays, aes(x='airport_name', y='Total_delays'))
  +geom_bar(stat='identity') #the stat= identity gives us the proper values
  +theme(
    axis_text_x=element_text(angle=20), 
    plot_title=element_text(size=25))
  +labs(title='Flights that are delayed at each airport')
)

```